gfx read elements "ellGlyphs_cxlines_geofit2_6612_bodycoordinates.exf"

gfx define field nuclearRegion_coordinates embedded element_xi elementxi_location field brainstem_coordinates

gfx define field marker_coordinates embedded element_xi marker_location field brainstem_coordinates
gfx define field d1 node_value fe_field brainstem_coordinates d/ds1
gfx define field d2 node_value fe_field brainstem_coordinates d/ds2
gfx define field d3 node_value fe_field brainstem_coordinates d/ds3
gfx define field orientation_scale composite d1 d2 d3
gfx define field dfd1 node_value fe_field coordinates d/ds1
gfx define field dfd2 node_value fe_field coordinates d/ds2
gfx define field dfd3 node_value fe_field coordinates d/ds3
gfx define field deformed_orientation_scale composite dfd1 dfd2 dfd3

gfx modify g_element "/" general clear;
gfx modify g_element "/" lines domain_mesh1d subgroup brainstem coordinate brainstem_coordinates face all tessellation default LOCAL line line_base_size 0 select_on material grey50 selected_material default_selected render_shaded;
gfx modify g_element "/" surfaces domain_mesh2d coordinate brainstem_coordinates face all tessellation default LOCAL select_on invisible material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_CENTRAL CANAL" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_INF CENTRAL N" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_POSTPYRAMIDAL NUCLEUS, RAPHE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R ABDUCENS NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L INF CEREBELLAR PEDUNCLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R INF CEREBELLAR PEDUNCLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L MID CEREBELLAR PEDUNCLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R MID CEREBELLAR PEDUNCLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SUP CEREBELLAR PEDUNCLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SUP CEREBELLAR PEDUNCLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L A-V COCHLEAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R A-V COCHLEAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L DOR COCHLEAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R DOR COCHLEAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L P-V COCHLEAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R P-V COCHLEAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L COCHLEAR GRAN LAYER" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R COCHLEAR GRAN LAYER" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L CUNEATE NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R CUNEATE NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L EX CUNEATE NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R EX CUNEATE NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L FACIAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R FACIAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L GRACILE NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R GRACILE NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L HYPOGLOSSAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R HYPOGLOSSAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L INFRATRIGEMINAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R INFRATRIGEMINAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L INF OLIVE COMPLEX" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R INF OLIVE COMPLEX" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L KOLLIKER-FUSE NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R KOLLIKER-FUSE NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L NUC-LAT LEMNISCUS (VEN DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R NUC-LAT LEMNISCUS (VEN DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L LAT RETICULAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R LAT RETICULAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L LAT RETICULAR NUC 2" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R LAT RETICULAR NUC 2" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L MARGINAL NUC, SUPERIOR CEREBELLAR PEDUNCLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R MARGINAL NUC, SUPERIOR CEREBELLAR PEDUNCLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L MED LONGITUDINAL BUNDLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R MED LONGITUDINAL BUNDLE" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L NUC AMBIGUUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R NUC AMBIGUUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L NUC INCERTUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R NUC INCERTUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L NUC INTERCALATUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R NUC INTERCALATUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L LOCUS COERULEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R LOCUS COERULEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L NUC PRAEPOSITUS HYPOGLOSSI" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R NUC PRAEPOSITUS HYPOGLOSSI" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L NUC RETROAMBIGUALIS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R NUC RETROAMBIGUALIS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L NUC TRACTUS SOLITARIUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R NUC TRACTUS SOLITARIUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L PONTINE GRAY (D-L DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R PONTINE GRAY (D-L DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L RETROFACIAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R RETROFACIAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SUP OLIVE COMPLEX (LAT NUC)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SUP OLIVE COMPLEX (LAT NUC)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SUP OLIVE COMPLEX (MED NUC)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SUP OLIVE COMPLEX (MED NUC)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SUP OLIVE COMPLEX (PREOLIVARY)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SUP OLIVE COMPLEX (PREOLIVARY)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L GIGANTOCELLULAR TEG FIELD" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R GIGANTOCELLULAR TEG FIELD" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L LAT TEGMENTAL FIELD" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R LAT TEGMENTAL FIELD" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L MAGNOCELLULAR TEGMENTAL FIELD" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R MAGNOCELLULAR TEGMENTAL FIELD" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L DOR TEGMENTAL NUC (PERICEN)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R DOR TEGMENTAL NUC (PERICEN)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L TEGMENTAL RETICULAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R TEGMENTAL RETICULAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SENSORY NUC OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SENSORY NUC OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L CAUDAL NUC, SPINAL TR OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R CAUDAL NUC, SPINAL TR OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L INTERPOLAR NUC, SPINAL TR OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R INTERPOLAR NUC, SPINAL TR OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L ORAL NUC, SPINAL TR OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R ORAL NUC, SPINAL TR OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L STRIA ACUSTICA" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R STRIA ACUSTICA" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L NUC, TRAPEZOID BODY" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R NUC, TRAPEZOID BODY" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L TRAPEZOID BODY" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R TRAPEZOID BODY" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L INF VESTIBULAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R INF VESTIBULAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L MED VESTIBULAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R MED VESTIBULAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L LAT VESTIBULAR NUC (DOR DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R LAT VESTIBULAR NUC (DOR DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R LAT VESTIBULAR NUC (VEN DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SUP VESTIBULAR NUC (MED DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SUP VESTIBULAR NUC (MED DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SUP VESTIBULAR NUC (LAT DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SUP VESTIBULAR NUC (LAT DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L DOR MOTOR NUC, VAGUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R DOR MOTOR NUC, VAGUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L DORSAL RESPIRATORY GROUP" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R DORSAL RESPIRATORY GROUP" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L LATERAL PARABRACHIAL NUCLEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R LATERAL PARABRACHIAL NUCLEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L MEDIAL PARABRACHIAL NUCLEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R MEDIAL PARABRACHIAL NUCLEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L PONTINE RESPIRATORY GROUP" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R PONTINE RESPIRATORY GROUP" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L RETROTRAPEZOID NUCLEUS/PARAFACIAL NUCLEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R RETROTRAPEZOID NUCLEUS/PARAFACIAL NUCLEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L BOTZINGER COMPLEX" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R BOTZINGER COMPLEX" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L PRE-BOTZINGER COMPLEX" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R PRE-BOTZINGER COMPLEX" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L rostral VRG" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R rostral VRG" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L caudal VRG" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R caudal VRG" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L VENTRAL RESPIRATORY GROUP" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R VENTRAL RESPIRATORY GROUP" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L MOTOR NUC OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R MOTOR NUC OF V" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SUP SALIVATORY NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SUP SALIVATORY NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material silver selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L INF SALIVATORY NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R INF SALIVATORY NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L EDINGER-WESTPHAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R EDINGER-WESTPHAL NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material magenta selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L OCULOMOTOR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R OCULOMOTOR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material white selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L TROCHLEAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R TROCHLEAR NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L ABDUCENS NUC" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material green selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L LAT VESTIBULAR NUC (VEN DIV)" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material cyan selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L SPINAL TRIGEMINAL NUCLEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R SPINAL TRIGEMINAL NUCLEUS" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material orange selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L COCHLEAR NUCLEI" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R COCHLEAR NUCLEI" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material yellow selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_L VESTIBULAR COMPLEX" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "xiGroups_R VESTIBULAR COMPLEX" coordinate nuclearRegion_coordinates tessellation default_points LOCAL glyph sphere size "0.098*0.098*0.098" offset 0,0,0 font default orientation orientation_scale scale_factors "1*1*1" select_on material red selected_material default_selected render_shaded;
gfx modify g_element "/" lines domain_mesh1d subgroup "nerve tracts" coordinate brainstem_coordinates face all tessellation default LOCAL line_width 4 line line_base_size 0 select_on invisible material gold selected_material default_selected render_shaded;
gfx modify g_element "/" points domain_nodes subgroup "tract group" coordinate brainstem_coordinates tessellation default_points LOCAL glyph none size "0.7*0.7*0.7" offset 0,0,0 font default label brainstem_region_name label_offset 0,0,0 select_on invisible material gold selected_material default_selected render_shaded;


gfx create window
gfx edit scene
